
# publish.ps1
#
# Publishes a web site to an AWS stack. This web site may use a database.
# Ensures that all necessary servers are installed through use of a AWS Cloudformation template.
# If the stack already exists, it is updated.
#
# Installs the code of the web site on the EC2 web servers. Updates its web.config file with the server name of the
# provisioned RDS database server. 
#
# Note that this script does not set any parameters in the template, except for the Version parameter and
# the DeploymentBucketName parameter - both required to deploy the web site code. This means that for all
# other parameters the default values are used.

Param(
  [Parameter(Mandatory=$True, HelpMessage="Version name of this deployment. Typically the version number generated by for example TeamCity")]
  [string]$version
)

write-host ">>>>$version<<<<<<"



